Update container.yml

diff --git a/.github/workflows/container.yml b/.github/workflows/container.yml
--- a/.github/workflows/container.yml
+++ b/.github/workflows/container.yml
@@ -48,12 +48,17 @@ jobs:
         blackduck_reports_sarif_create: true
         blackduck_upload_sarif_report: true
         github_token: ${{ secrets.GITHUB_TOKEN }}
-        # blackduck_trust_cert: true
+      continue-on-error: true
 
-        ### SARIF report generation and upload to GitHub Advanced Security
-        # blackduck_reports_sarif_create: true # Create Black Duck SARIF report and upload it as artifact
-        # blackduck_upload_sarif_report: true # Upload Black Duck SARIF report in GitHub Advanced Security tab
-        # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when blackduck_upload_sarif_report is set as true
+    - name: Check SCA Scan Result
+      if: always()
+      run: |
+        if grep -q "File .bridge/Blackduck SARIF Generator/report.sarif.json does not exist" <<<"${{ steps.sca-scan.outputs.stdout }}"; then
+          echo "SARIF file not found, continuing execution."
+        else
+          exit 1
+        fi
+  
     - name: Pause for Debugging
       if: failure()
       run: sleep 1h
